### ISSUE TITLE
Incorrect sample names in selfSM output from BAM files with SM as last item

### ISSUE THREAD

**Issue by chapmanb** [Griffan/VerifyBamID#10]
Thanks for this updated version of VerifyBamID, it's nice to have pre-built distributions to use as inputs and really eases use for the general case. We've incorporate VerifyBamID2 into bcbio and are running into an issue with input BAMs that have the `SM` tag at the end of the read group:
```
@RG     ID:Test1        PL:illumina     PU:Test1        SM:Test1
@PG     ID:bwa  PN:bwa
```
This code for parsing SM reads until the next tab:

https://github.com/Griffan/VerifyBamID/blob/fcbf628343ff4e4c725e7a89bc4195f10bed036a/SimplePileupViewer.cpp#L345

resulting in parsing out `Test1\n@PG` as the sample name, which results in an extraneous newline inserted in the output. https://github.com/bcbio/bcbio-nextgen/issues/2417#issuecomment-396704195 has an example of the issue.

Would it be possible to adjust to stop on either newline or a tab here to avoid the problem? Thanks much for the help.

**Comment by Griffan** [comment]
Thanks for your feedback! 
The problem has been fixed. 
Please let us know if there exist a further problem

**Comment by chapmanb** [comment]
Brilliant, thanks so much for the quick fix. I pushed an updated bioconda package with these fixes. I appreciate the quick help and all your hard work.
