### ISSUE TITLE
initialization fail to parse region

### ISSUE THREAD

**Issue by ZjmaNMU** [Griffan/VerifyBamID#11]
When I used VerifyBamID I got many message like this:

[Warning::SIMPLEmpileup] initialization fail to parse region '2:219253897-219253897' with /XXX/XX.bam, skip...

It seems like skipping all.
What does it mean? Is there anything wrong with the BAM file? How to deal with it?
Thanks

**Comment by Griffan** [comment]
Have you checked the build version of the coordinate system between the resource file and the bam file?
