### ISSUE TITLE
question ！！！！！

### ISSUE THREAD

**Issue by feihongloveworld** [Griffan/VerifyBamID#12]
hi sir：
     the result of example in soft as below：
     ################
     Estimation from OptimizeHeter:
     Contaminating Sample PC1:0      PC2:0   
     Intended Sample PC1:0   PC2:0   
     Alpha:0.5
    ### the command ：
   VerifyBamID-1.0.5/bin/VerifyBamID" "--DisableSanityCheck" "--UDPath" 
  "resource/test/hapmap_3.3.b37.dat.UD" "--BamFile" "resource/test/test.bam" "--BedPath" "
    Directory: /GPFS01/home/feih/bin/VerifyBamID-1.0.5
    ################
   my true example result is same as it，is there any problem ？？？
   #####

**Comment by Griffan** [comment]
May I ask what function are you trying to use:
1. contamination level estimation 
2. new resource files generation


If you are up to 1, you can either provide resource file with
```
$(VERIFY_BAM_ID_HOME)/bin/VerifyBamID --BamFile [/path/to/bam/or/cram/file] --SVDPrefix [/path/to/SVDPrefix/file] --Reference [/path/to/fasta/file]
```
or

```
$(VERIFY_BAM_ID_HOME)/bin/VerifyBamID --UDPath [/path/to/UD/file] --BamFile [/path/to/bam/or/cram/file] --BedPath [/path/to/bed/file] --MeanPath [/path/to/mu/file] --Reference [/path/to/fasta/file]
```

**Comment by feihongloveworld** [comment]
hi sir：
       i want to get contamination level estimation and  use the command as your recommand.
       but the result is not good.....
       so i need your  help.
########
VERIFY_BAM_ID_HOME=/GPFS01/home/feih/bin/VerifyBamID-1.0.5
BAM=/GPFS05/Re-WES.sorted.rmdup.realigned.recal.bam
${VERIFY_BAM_ID_HOME}/bin/VerifyBamID \
        --DisableSanityCheck \
        --UDPath $VERIFY_BAM_ID_HOME/resource/1000g.100k.b37.vcf.gz.dat.UD \
        --BamFile $BAM\
        --BedPath $VERIFY_BAM_ID_HOME/resource/1000g.100k.b37.vcf.gz.dat.bed \
        --MeanPath $VERIFY_BAM_ID_HOME/resource/1000g.100k.b37.vcf.gz.dat.mu \
        --Reference /GPFS01/databases/hs37d5/bwa_index/hs37d5.fa
############

**Comment by Griffan** [comment]
Do you still get all "0" estimation? 
Would you mind to provide more detailed information? By the way, if you do not specify --DisableSanityCheck, it might give you some clue about your bam file.

**Comment by feihongloveworld** [comment]
hi sir:
   the detail of selSM file as below:
#################
#SEQ_ID	B181118162127-CLN-KY556-KY598-Re-WES
RG	NA
CHIP_ID	NA
#SNPS	99976
#READS	250445
AVG_DP	37.3297
FREEMIX	0.5
FREELK1	-0
FREELK0	-0
##################

**Comment by Griffan** [comment]
Did you see any warning information in log file? Like inconsistency of reference build version. 
Have you tried this on other bam files, is this bam specific?
Another way to debug is to specify --OutputPileup to see if the bases coverage are normal.

**Comment by feihongloveworld** [comment]
hi sir：
     the informatios from “make test”：
    ####################################
   make test
   Running tests...
   Test project /GPFS01/home/feih/bin/VerifyBamID-1.0.5
    Start 1: myTest1
   1/1 Test #1: myTest1 ..........................   Passed    0.96 sec
   100% tests passed, 0 tests failed out of 1
   Total Test time (real) =   0.97 sec
  #### 
  the lasttest.log file as below:
 #######
Estimation from OptimizeHeter:
Contaminating Sample PC1:0      PC2:0   
Intended Sample PC1:0   PC2:0   
Alpha:0.5
NOTICE - Success!
<end of output>
Test time =   0.96 sec
----------------------------------------------------------
Test Passed.
"myTest1" end time: Jan 31 08:53 CST
"myTest1" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jan 31 08:53 CST

**Comment by feihongloveworld** [comment]
hi sir:
      linux information as below:
     ############
cat /proc/version
Linux version 3.10.0-327.el7.x86_64 (mockbuild@x86-034.build.eng.bos.redhat.com) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Oct 29 17:29:29 EDT 2015
########
cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
#######################
thank you for your attantion ！！！！

**Comment by feihongloveworld** [comment]
hi sir：
   i really really need your help !!! /泪奔

**Comment by Griffan** [comment]
I'm trying to reproduce your problem. Is your git repo at the most updated commit?

**Comment by Griffan** [comment]
Hi, I set up virtual machine to match your environment，but I still cannot reproduce your problem.
On the other hand, in the latest git repo version, the compiled executable doesn't have 1.0.5 as suffix(shown in your post), could you double check if you are installing the tool from most updated git commit?
Thanks!
