### ISSUE TITLE
can this software handle  panel(~100k) data

### ISSUE THREAD

**Issue by GSBaohuaGu** [Griffan/VerifyBamID#14]
Can this software handle  panel(~100k) data? when I use the 1000g.phase3.100k.b37.vcf.gz as resource compute no contamination sample ,the result is 0.479. I want to know if I compute panel sample conmination, I must build my own database?
How to bulid my  resource files, can you give a example of  ReferencePanel.vcf.gz data?
VerifyBamID --RefVCF ReferencePanel.vcf.gz --Reference ./resource/test/chr20.fa.gz

**Comment by Griffan** [comment]
Hi, if you mean use a reference vcf with sample size 100k, I haven't tried this scale yet. I think the memory will be too large to run. 
If failed, you can try to split the vcf files following the tutorial of partial SVD for dealing large number of markers, but the method should work for your case I think. Either way you should run this process on a large mem machine.

**Comment by GSBaohuaGu** [comment]
Thank you very much!
Are you Chinese, I may not make in clear in English.
can I speak Chinese?
我现在处理wes的数据，主要是针对某一个癌种设计的探针的数据，我们的探针（~100k）特别的小，针对这样的数据软件可以测试吗？
还有一个问题是对于我们没有污染的数据，软件测试的结果会出现污染的情况，你们有出现过这种情况吗？



谷宝华 | Baohua Gu
生物信息分析工程师   |  Specialist, Bioinformatics Department   
世和基因生物技术有限公司 | Geneseeq Technology Inc.
电话 | Tel: +86-151-0519-8252
电邮 | Email: baohua.gu@geneseeq.com
网址 | Website: www.geneseeq.com

This email message and any documents accompanying this transmission may contain privileged and/or confidential information and is intended solely for the addressee(s) named above. If you are not the intended addressee/recipient, you are hereby notified that any use of, disclosure, copying, distribution, or reliance on the contents of this EMail information is strictly prohibited and may result in legal action against you. Please reply to the sender advising of the error in transmission and immediately delete/destroy the message and any accompanying documents. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the Company. The Company accepts no liability for any damage caused by the transmission of this e-mail. 
 
From: Griffan(Fan Zhang)
Date: 2019-04-04 11:24
To: Griffan/VerifyBamID
CC: BaohuaGu; Author
Subject: Re: [Griffan/VerifyBamID] can this software handle panel(~100k) data (#14)
Hi, if you mean use a reference vcf with sample size 100k, I haven't tried this scale yet. I think the memory will be too large to run.
If failed, you can try to split the vcf files following the tutorial of partial SVD for dealing large number of markers, but the method should work for your case I think. Either way you should run this process on a large mem machine.

**Comment by Griffan** [comment]
yes, you need to construct customized resource file using your own marker set. The problem in your case is very likely due to insufficient overlap between marker set and bam file.
你的这种情况应该是需要重新建resource files， 尽量用和你的探针有重合的位点。

**Comment by GSBaohuaGu** [comment]
hi:
sorry to bother you. 
lung cancer panel sequencing(panel ~139)
I retained reads from the targeted sample with probability 1-a, and from the contaminating sample with probability
a ranging from 0%(uncontamination),1% ,2%,3%,4%,5%,6%,7%,8%,9%,10%, 15%,20%,30%
X axis:1-a
Y axis:software calculation results
verifyBamID(result.selfSM#READS~300snps) :Low level contamination will be errors in judgment.but the result of VerifyBamID2(result.selfSM#READS~300snps) is on the right.  


谷宝华 | Baohua Gu
生物信息分析工程师   |  Specialist, Bioinformatics Department   
世和基因生物技术有限公司 | Geneseeq Technology Inc.
电话 | Tel: +86-151-0519-8252
电邮 | Email: baohua.gu@geneseeq.com
网址 | Website: www.geneseeq.com

This email message and any documents accompanying this transmission may contain privileged and/or confidential information and is intended solely for the addressee(s) named above. If you are not the intended addressee/recipient, you are hereby notified that any use of, disclosure, copying, distribution, or reliance on the contents of this EMail information is strictly prohibited and may result in legal action against you. Please reply to the sender advising of the error in transmission and immediately delete/destroy the message and any accompanying documents. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the Company. The Company accepts no liability for any damage caused by the transmission of this e-mail. 
 
From: Griffan(Fan Zhang)
Date: 2019-04-04 12:03
To: Griffan/VerifyBamID
CC: BaohuaGu; Author
Subject: Re: [Griffan/VerifyBamID] can this software handle panel(~100k) data (#14)
yes, you need to construct customized resource file using your own marker set. The problem in your case is very likely due to insufficient overlap between marker set and bam file.
你的这种情况应该是需要重新建resource files， 尽量用和你的探针有重合的位点。
