### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by seppinho** [Griffan/VerifyBamID#15]
Hi, 
I tried to compile the master branch on Ubuntu 18 (gcc 7.3.0, libcurl4) but cmake failed with 'libcurl library not found'. 
I also tested the latest release which gives me:
./VerifyBamID.Linux: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./VerifyBamID.Linux)

Thanks for your help!

**Comment by Griffan** [comment]
Hi,
the CMake will try to find libcurl in these default directories:
```
/usr/lib/x86_64-linux-gnu/ 
/usr/lib/ 
/usr/lib64/
```
if you didn't install your libcurl in these dirs, you can try to specify:

`cmake  ..  -DCURLLIB =/bzip2_absolute_path/lib/libcurl.a`

**Comment by seppinho** [comment]
Thanks, that solved my issue!
