### ISSUE TITLE
incorrect PCA coordinate for samples

### ISSUE THREAD

**Issue by yuqiu77** [Griffan/VerifyBamID#16]
I try to use verifyBamID2 1.05 to identify ancestry and potential contamination of some WGS and WES samples.  The PC1/PC2 coordinates of intended samples reported are way off.  For example, I checked a NA24143 WES bam file:

/opt/conda/share/verifybamid2-1.0.5-3/VerifyBamID --BamFile NA24143.wes.bam \
--Reference /ref/Homo_sapiens/b37/decoy/genome/genome.fa \
--SVDPrefix /opt/conda/share/verifybamid2-1.0.5-3/resource/1000g.100k.b37.vcf.gz.dat \
--Output NA24143

NOTICE - Number of marker in Reference Matrix:99976
NOTICE - Number of marker shared with input file:30458
NOTICE - Mean Depth:15.383643
NOTICE - SD Depth:42.680393
NOTICE - 29563 SNP markers remained after sanity check.
NOTICE - Passing Marker Sanity Check...
Estimation from OptimizeHeter:
Contaminating Sample PC1:-13.7537       PC2:-223.271
Intended Sample PC1:-0.011974   PC2:-0.0259268
Alpha:6.72715e-05
NOTICE - Success!

NA24143 is Caucasian and I expected that the PC2 is around 0.025 instead of -0.025.  

I also run the package on over 50 WGS samples.  Most of them should be Caucasian.   However, the PC coordinates generated are closer to east asian again:

![image](https://user-images.githubusercontent.com/17089239/61067076-c3824700-a3d4-11e9-9c66-4fe337c8eb96.png)

**Comment by yuqiu77** [comment]
Never mind.  I previously used the version from bioconda.  compile from git directly seems resolve the issue.

**Comment by Griffan** [comment]
I think it is because the resource file you used is not updated. Glad that you resolved it.
