### ISSUE TITLE
 Installation error

### ISSUE THREAD

**Issue by GSBaohuaGu** [Griffan/VerifyBamID#17]
In file included from /usr/include/c++/4.8.2/unordered_map:35:0,
                 from /GPFS02/gubh/softwares/VerifyBamID-master/ContaminationEstimator.h:28,
                 from /GPFS02/gubh/softwares/VerifyBamID-master/main.cpp:26:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /GPFS02/gubh/softwares/VerifyBamID-master/ContaminationEstimator.h:32:0,
                 from /GPFS02/gubh/softwares/VerifyBamID-master/main.cpp:26:
/GPFS02/gubh/softwares/VerifyBamID-master/SimplePileupViewer.h:47:9: error: ‘unordered_map’ in namespace ‘std’ does not name a type
 typedef std::unordered_map<std::string, std::unordered_map<int, std::pair<char, char> > > BED;
         ^
/GPFS02/gubh/softwares/VerifyBamID-master/SimplePileupViewer.h:55:5: error: ‘BED’ does not name a type
     BED bedTable;
     ^
/GPFS02/gubh/softwares/VerifyBamID-master/SimplePileupViewer.h:62:26: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     std::string SEQ_SM = "DefaultSampleName";
                          ^
/GPFS02/gubh/softwares/VerifyBamID-master/SimplePileupViewer.h:63:20: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     int numBases = 0;
                    ^
/GPFS02/gubh/softwares/VerifyBamID-master/SimplePileupViewer.h:64:28: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     int effectiveNumSite = 0;
                            ^
/GPFS02/gubh/softwares/VerifyBamID-master/SimplePileupViewer.h:65:23: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [enabled by default]
     double avgDepth = 0;
........
/usr/include/c++/4.8.2/fstream:625:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/4.8.2/fstream:599:11: note: std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/usr/include/c++/4.8.2/fstream:599:11: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to const std::basic_ofstream<char>&’
make[2]: *** [CMakeFiles/VerifyBamID.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/VerifyBamID.dir/all] Error 2
make: *** [all] Error 2
How to solve？
Thank you very much!

**Comment by Griffan** [comment]
Hi, 
It's very likely due to the old version of gcc/g++.
your can refer to this issue(https://github.com/Griffan/FASTQuick/issues/10) which shared the same problem.

**Comment by Griffan** [comment]
@GSBaohuaGu have you resolved this problem yet?

**Comment by GSBaohuaGu** [comment]
Hi:
I haven't solved this problem, gcc version upgrade is hard. I don’t have root authority. Our cluster is managed uniformly. I have other things recently, later I will have a try.

Thank you for your concern.



谷宝华 | Baohua Gu
生物信息分析工程师   |  Specialist, Bioinformatics Department   
世和基因生物技术有限公司 | Geneseeq Technology Inc.
电话 | Tel: +86-151-0519-8252
电邮 | Email: baohua.gu@geneseeq.com
网址 | Website: www.geneseeq.com

This email message and any documents accompanying this transmission may contain privileged and/or confidential information and is intended solely for the addressee(s) named above. If you are not the intended addressee/recipient, you are hereby notified that any use of, disclosure, copying, distribution, or reliance on the contents of this EMail information is strictly prohibited and may result in legal action against you. Please reply to the sender advising of the error in transmission and immediately delete/destroy the message and any accompanying documents. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the Company. The Company accepts no liability for any damage caused by the transmission of this e-mail. 
 
From: Griffan(Fan Zhang)
Date: 2020-07-21 00:12
To: Griffan/VerifyBamID
CC: BaohuaGu; Mention
Subject: Re: [Griffan/VerifyBamID] Installation error (#17)
@GSBaohuaGu have you resolved this problem yet?
