### ISSUE TITLE
VerifyBamID libstdc++.so.6 version issues

### ISSUE THREAD

**Issue by GuoTingYou** [Griffan/VerifyBamID#19]
I used VerifyBamID to check if there are contaminations in my samples' BAM files but got the following error massages:

```
/my/path/to/VerifyBamID: /usr/lib64/libstdc++.so.6: version 'CXXABI_1.3.8' not found (required by /my/path/to/VerifyBamID)
/my/path/to/VerifyBamID: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.18' not found (required by /my/path/to/VerifyBamID)
/my/path/to/VerifyBamID: /usr/lib64/libstdc++.so.6: version 'CXXABI_1.3.5' not found (required by /my/path/to/VerifyBamID)
/my/path/to/VerifyBamID: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by /my/path/to/VerifyBamID)
/my/path/to/VerifyBamID: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by /my/path/to/VerifyBamID)
```

I google my problem and it seemed that I used a lower version of libstdc++. I've tried to solve the problem by the following:

1. Add `export LD_LIBRARY_PATH="/new/version/gcc-5.2.0/lib64/libstdc++.so.6":$LD_LIBRARY_PATH` to my `~/.bashrc` file.
2. Add `LD_PRELOAD="/new/version/gcc-5.2.0/lib64/libstdc++.so.6"` in my VerifyBamID pipeline script.

However, neither did them work. Can anyone help me to solve the problem? Thanks.
P.S. My operating system: Linux version 2.6.32-696.30.1.el6.x86_64

**Comment by Griffan** [comment]
Have you tried to compile VB2 from source file? 
Have you tried to export a higher version of gcc libs?

**Comment by GuoTingYou** [comment]
Thank you very much.
I haven't tried to compile VB2 but exported a higher version of gcc libs did work.
