### ISSUE TITLE
Guidance on RNA-Seq / Tumor Data

### ISSUE THREAD

**Issue by sstadick** [Griffan/VerifyBamID#20]
Hello!

In your paper you mention that:

> There are other possible useful extensions to our joint contamination and estimation method. We are extending these methods to detect and estimate contamination for RNA-seq and other epigenomic sequence data. The method can also be extended to handle contamination in cancer genomic data. 

Do you have any guidance or suggestions on how to run verifybamid2 in either of those scenarios?

**Comment by hyunminkang** [comment]
For RNA-seq, if you run it as if it is an exome sequence data, it should
work reasonably well. For other omics data, you just need to change the
regions to focus on the regions you expect. There are room for
optimization, but should run well out of the box.

Hyun.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by nh13** [comment]
@hyunminkang how about for somatic data, where we do not expect heterozygous sites to have 50% allele frequency.  In the previous version of `verifyBamId`, we could input the called genotypes.

**Comment by hyunminkang** [comment]
verifyBamID2 does not (yet) have a routine to check with genotypes
unfortunately.

You can still use verifyBamID1 to perform such analysis.

Hyun.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : hmkang@umich.edu

**Comment by sstadick** [comment]
@hyunminkang thanks for taking the time to respond! I will use verifyBamID1 for now for somatic data.
