### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Myskiper** [Griffan/VerifyBamID#21]
i git clone and cmake -DHTS_INCLUDE_DIRS=/envs/htslib/include/ -DHTS_LIBRARIES=/envs/htslib/lib/libhts.a ..
after make, I got this:
Scanning dependencies of target statgen
[  1%] Building CXX object statgen/CMakeFiles/statgen.dir/BaseAsciiMap.cpp.o
[  3%] Building CXX object statgen/CMakeFiles/statgen.dir/BaseUtilities.cpp.o
[  5%] Building CXX object statgen/CMakeFiles/statgen.dir/BgzfFileType.cpp.o
[  7%] Building CXX object statgen/CMakeFiles/statgen.dir/BgzfFileTypeRecovery.cpp.o
[  8%] Building CXX object statgen/CMakeFiles/statgen.dir/CharBuffer.cpp.o
[ 10%] Building CXX object statgen/CMakeFiles/statgen.dir/Cigar.cpp.o
[ 12%] Building CXX object statgen/CMakeFiles/statgen.dir/CigarRoller.cpp.o
[ 14%] Building CXX object statgen/CMakeFiles/statgen.dir/Error.cpp.o
[ 15%] Building CXX object statgen/CMakeFiles/statgen.dir/ErrorHandler.cpp.o
[ 17%] Building CXX object statgen/CMakeFiles/statgen.dir/FileType.cpp.o
[ 19%] Building CXX object statgen/CMakeFiles/statgen.dir/Generic.cpp.o
[ 21%] Building CXX object statgen/CMakeFiles/statgen.dir/GenomeSequence.cpp.o
[ 22%] Building CXX object statgen/CMakeFiles/statgen.dir/GzipFileType.cpp.o
[ 24%] Building CXX object statgen/CMakeFiles/statgen.dir/GzipHeader.cpp.o
[ 26%] Building CXX object statgen/CMakeFiles/statgen.dir/Hash.cpp.o
[ 28%] Building CXX object statgen/CMakeFiles/statgen.dir/IndexBase.cpp.o
[ 29%] Building CXX object statgen/CMakeFiles/statgen.dir/InputFile.cpp.o
[ 31%] Building CXX object statgen/CMakeFiles/statgen.dir/IntArray.cpp.o
[ 33%] Building CXX object statgen/CMakeFiles/statgen.dir/MathMatrix.cpp.o
[ 35%] Building CXX object statgen/CMakeFiles/statgen.dir/MathVector.cpp.o
[ 36%] Building CXX object statgen/CMakeFiles/statgen.dir/MemoryMap.cpp.o
[ 38%] Building CXX object statgen/CMakeFiles/statgen.dir/MemoryMapArray.cpp.o
[ 40%] Building CXX object statgen/CMakeFiles/statgen.dir/PhoneHome.cpp.o
[ 42%] Building CXX object statgen/CMakeFiles/statgen.dir/STLUtilities.cpp.o
[ 43%] Building CXX object statgen/CMakeFiles/statgen.dir/Sort.cpp.o
[ 45%] Building CXX object statgen/CMakeFiles/statgen.dir/StatGenStatus.cpp.o
[ 47%] Building CXX object statgen/CMakeFiles/statgen.dir/StringArray.cpp.o
[ 49%] Building CXX object statgen/CMakeFiles/statgen.dir/StringBasics.cpp.o
[ 50%] Building CXX object statgen/CMakeFiles/statgen.dir/StringHash.cpp.o
[ 52%] Building CXX object statgen/CMakeFiles/statgen.dir/Tabix.cpp.o
[ 54%] Building CXX object statgen/CMakeFiles/statgen.dir/UncompressedFileType.cpp.o
[ 56%] Building C object statgen/CMakeFiles/statgen.dir/knetfile.c.o
[ 57%] Linking CXX static library libstatgen.a
[ 57%] Built target statgen
Scanning dependencies of target Vcf
[ 59%] Building CXX object libVcf/CMakeFiles/Vcf.dir/libVcfVcfFile.cpp.o
[ 61%] Linking CXX static library libVcf.a
[ 61%] Built target Vcf
Scanning dependencies of target samtools
[ 63%] Building C object samtools/CMakeFiles/samtools.dir/bam.c.o
[ 64%] Building C object samtools/CMakeFiles/samtools.dir/bam_aux.c.o
[ 66%] Building C object samtools/CMakeFiles/samtools.dir/bam_index.c.o
[ 68%] Building C object samtools/CMakeFiles/samtools.dir/bam_mate.c.o
[ 70%] Building C object samtools/CMakeFiles/samtools.dir/bam_md.c.o
[ 71%] Building C object samtools/CMakeFiles/samtools.dir/bam_sort.c.o
[ 73%] Building C object samtools/CMakeFiles/samtools.dir/bam_stat.c.o
[ 75%] Building C object samtools/CMakeFiles/samtools.dir/bamtk.c.o
[ 77%] Building C object samtools/CMakeFiles/samtools.dir/bedidx.c.o
[ 78%] Building C object samtools/CMakeFiles/samtools.dir/kprobaln.c.o
[ 80%] Building C object samtools/CMakeFiles/samtools.dir/sam_opts.c.o
[ 82%] Building C object samtools/CMakeFiles/samtools.dir/sample.c.o
[ 84%] Linking C static library libsamtools.a
[ 84%] Built target samtools
Scanning dependencies of target VerifyBamID
[ 85%] Building CXX object CMakeFiles/VerifyBamID.dir/main.cpp.o
[ 87%] Building CXX object CMakeFiles/VerifyBamID.dir/SVDcalculator.cpp.o
[ 89%] Building CXX object CMakeFiles/VerifyBamID.dir/ContaminationEstimator.cpp.o
[ 91%] Building CXX object CMakeFiles/VerifyBamID.dir/MathGenMin.cpp.o
[ 92%] Building CXX object CMakeFiles/VerifyBamID.dir/MathGold.cpp.o
[ 94%] Building CXX object CMakeFiles/VerifyBamID.dir/Random.cpp.o
[ 96%] Building CXX object CMakeFiles/VerifyBamID.dir/SimplePileupViewer.cpp.o
[ 98%] Building CXX object CMakeFiles/VerifyBamID.dir/params.cpp.o
[100%] Linking CXX executable ../bin/VerifyBamID
/usr/bin/ld: BFD version 2.20.51.0.2-5.47.el6_9.1 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: 错误：ld 返回 1
make[2]: *** [../bin/VerifyBamID] 错误 1
make[2]: *** 正在删除文件“../bin/VerifyBamID”
make[1]: *** [CMakeFiles/VerifyBamID.dir/all] 错误 2
make: *** [all] 错误 2

i also try to install from conda (https://anaconda.org/bioconda/verifybamid2), but i always met this error:
/envs/VerifyBamID2/bin/verifybamid2 --RefVCF ReferencePanel.vcf.gz --Reference ./resource/test/chr20.fa.gz
VerifyBamID2: A robust tool for DNA contamination estimation from sequence reads using ancestry-agnostic method.

 Version:1.0.6
 Copyright (c) 2009-2018 by Hyun Min Kang and Fan Zhang
 This project is licensed under the terms of the MIT license.

The following parameters are available.  Ones with "[]" are in effect:

Available Options
                    Input/Output Files : --BamFile [Empty],
                                         --PileupFile [Empty],
                                         --Reference [Empty],
                                         --SVDPrefix [/envs/VerifyBamID2/share/verifybamid2-1.0.6-2/resource/--RefVCF.ReferencePanel.vcf.gz.--Reference.vcf.gz.dat],
                                         --Output [result]
               Model Selection Options : --WithinAncestry,
                                         --DisableSanityCheck, --NumPC [2],
                                         --FixPC [Empty],
                                         --FixAlpha [-1.0e+00],
                                         --KnownAF [Empty], --NumThread [4],
                                         --Seed [12345], --Epsilon [1.0e-08],
                                         --OutputPileup, --Verbose
   Construction of SVD Auxiliary Files : --RefVCF [Empty]
                    Deprecated Options : --UDPath [Empty], --MeanPath [Empty],
                                         --BedPath [Empty]

Cannot correspond command line parameter ./resource/test/chr20.fa.gz (#3) to any of the options

FATAL ERROR -
Problems encountered parsing command line:

Cannot correspond command line parameter ./resource/test/chr20.fa.gz (#3) to any of the options

Exiting due to ERROR:
        Exception was thrown

**Comment by Griffan** [comment]
Thanks for the feedback. 
The first issue seems to be related to ld, the solution could be to upgrade ld or install binutil using conda.

The second issue is true. I will try to fix it. But I think this bug only relates to building customized resource files, if you just need estimation, you should still be able to use it.

**Comment by Myskiper** [comment]
Thank you for your quickly reply!
Cause I get some bams which aligned to UCSC hg19, I try to generate resource files from our reference genome.

**Comment by Griffan** [comment]
@Myskiper I think now the recipe has been updated and synced, you should be able to use --RefVCF option directly now. Please let me know otherwise.
Note that you may need to add conda-forge channel into the installing cmdline:
```
conda install -c bioconda -c conda-forge verifybamid2
```

**Comment by Myskiper** [comment]
thank you!  i reinstall and it work fine!
And i test some bam file, But I met warn:
Insufficient Available markers, check input bam depth distribution in output pileup file after specifying --OutputPileup

Dose this mean VerifyBamID can't check this kind of bam Because it interrupt. I test five bam, and met two.

**Comment by Griffan** [comment]
This only means that your bam files have very few overlapping markers with your resource files.
You can either disable sanity check( with --DisableSanityCheck) or prepare you customized resource files in restricted regions where the sequences are captured from.

**Comment by Myskiper** [comment]
Thank you very much! I'll try it!
