### ISSUE TITLE
create reference 

### ISSUE THREAD

**Issue by Myskiper** [Griffan/VerifyBamID#22]
hello,
       I want to create a reference. Cause the genotype file too large, I try to create by every chrom. But met three problem:
       First,
       VerifyBamID2: A robust tool for DNA contamination estimation from sequence reads using ancestry-agnostic method.

 Version:1.0.6
 Copyright (c) 2009-2018 by Hyun Min Kang and Fan Zhang
 This project is licensed under the terms of the MIT license.

The following parameters are available.  Ones with "[]" are in effect:

Available Options
                    Input/Output Files : --BamFile [Empty],
                                         --PileupFile [Empty],
                                         --Reference [/pub/database/ftp.ncbi.nih.gov/1000genomes/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa],
                                         --SVDPrefix [Empty],
                                         --Output [result]
               Model Selection Options : --WithinAncestry,
                                         --DisableSanityCheck, --NumPC [2],
                                         --FixPC [Empty],
                                         --FixAlpha [-1.0e+00],
                                         --KnownAF [Empty], --NumThread [6],
                                         --Seed [12345], --Epsilon [1.0e-08],
                                         --OutputPileup, --Verbose
   Construction of SVD Auxiliary Files : --RefVCF [/index/GRCH38/ALL.chr1.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz]
                    Deprecated Options : --UDPath [Empty], --MeanPath [Empty],
                                         --BedPath [Empty]

NOTICE - Specified --RefVCF reference panel VCF file, doing SVD on the fly...
NOTICE - This procedure will generate SVD matrices as [RefVCF path].UD and [RefVCF path].mu
NOTICE - You may specify --SVDPrefix [RefVCF path](or --UDPath [RefVCF path].UD and --MeanPath [RefVCF path].mu) in future use
Exiting due to ERROR:
        std::bad_alloc

Second, I try to give more resource to 20GB and 8 cpu, got error verifybamid2: line 33: 40028 已杀死               $DIR/VerifyBamID "$@"

Third,
with GRCH37:ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.filter.vcf.gz, Duplicated Marker at 1:9176790 make it interrupt

**Comment by Griffan** [comment]
Hi, @Myskiper 
It's recommended to only use a small subset of the markers in 1000g phase3 genotype VCF, usually 10k - 100k would be sufficient. You can subset the VCF file based on your target region first and then feed it into VB2. (BTW, this process can be automatically done in the [FASTQuick](https://github.com/Griffan/FASTQuick#getting-started) index step)

In case you really need to build resource files based on a huge reference VCF, you can refer to https://github.com/Griffan/VerifyBamID#need-more-markers
