### ISSUE TITLE
chr prefix in resources files

### ISSUE THREAD

**Issue by shadrinams** [Griffan/VerifyBamID#26]
Hello,

I am planning to run VerifyBamID for BAM files aligned with GRCh37 **with** chr prefix. Is there a simple way to create the VerifyBamID resource files for GRCh37 with chr prefix? 
Thank you.

**Comment by Griffan** [comment]
If the coordinate systems are the same, you only need to add "chr" prefix in the existing ".bed" file( one of the resource files).
