### ISSUE TITLE
Bam is either very-very shallow, or aligned to the wrong reference

### ISSUE THREAD

**Issue by jazberna1** [Griffan/VerifyBamID#27]
Dear VerifyBamID team,

I have run VerifyBamID Version:2.0.1 on a mtDNA bam file and got the following message:
_Found zero likelihoods. Bam is either very-very shallow, or aligned to the wrong reference (relative to the vcf)_

It turns out that because of the way we amplify the mtDNA there can be differences of coverage as the one in this plot.
![Captura de pantalla de 2021-05-26 11-52-44](https://user-images.githubusercontent.com/27732589/119644100-cc3f6300-be1c-11eb-9250-ea45bf8b8f3d.png)

I was wondering if that may explain the error and if there is a way to relax VerifyBamID so it does not complain about coverage.

This is how I called VerifyBamID

```
 VerifyBamID \
--Verbose \
--NumPC 4 \
--Output 20100322.GRCh38DH.preBqsr \
--BamFile 20100322.GRCh38DH.aligned.duplicate_marked.sorted.bam \
--Reference Homo_sapiens_assembly38.fasta \
--UDPath Homo_sapiens_assembly38.contam.UD \
--MeanPath Homo_sapiens_assembly38.contam.mu \
--BedPath Homo_sapiens_assembly38.contam.bed \
--DisableSanityCheck 

```
Many thanks,
Jorge

**Comment by hyunminkang** [comment]
Hi Jorge, I don't think verifyBamID can be used for mtDNA. It is meant to
run on autosomes.

Hyun.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : ***@***.***

**Comment by jazberna1** [comment]
Hello Hyun,

Thanks so much for replying so fast! Understood.

Regards
Jorge
