### ISSUE TITLE
Getting the error message during the installation.

### ISSUE THREAD

**Issue by omG0-hub** [Griffan/VerifyBamID#28]
Hello, 

I will use the v1 to verify the sample contamination, In this time, I will try to test V2 for taking better results.
I am getting the following error message during the installation. 

Scanning dependencies of target statgen
[  1%] Building CXX object statgen/CMakeFiles/statgen.dir/StringHash.cpp.o
[  3%] Building CXX object statgen/CMakeFiles/statgen.dir/InputFile.cpp.o
[  5%] Building CXX object statgen/CMakeFiles/statgen.dir/BaseUtilities.cpp.o
[  7%] Building CXX object statgen/CMakeFiles/statgen.dir/GenomeSequence.cpp.o
[  9%] Building CXX object statgen/CMakeFiles/statgen.dir/Hash.cpp.o
[ 11%] Building CXX object statgen/CMakeFiles/statgen.dir/PhoneHome.cpp.o
[ 13%] Building CXX object statgen/CMakeFiles/statgen.dir/MemoryMapArray.cpp.o
[ 15%] Building CXX object statgen/CMakeFiles/statgen.dir/Error.cpp.o
[ 16%] Building CXX object statgen/CMakeFiles/statgen.dir/STLUtilities.cpp.o
[ 18%] Building CXX object statgen/CMakeFiles/statgen.dir/StringArray.cpp.o
[ 20%] Building CXX object statgen/CMakeFiles/statgen.dir/FileType.cpp.o
[ 22%] Building CXX object statgen/CMakeFiles/statgen.dir/GzipFileType.cpp.o
[ 24%] Building CXX object statgen/CMakeFiles/statgen.dir/ErrorHandler.cpp.o
[ 26%] Building CXX object statgen/CMakeFiles/statgen.dir/MemoryMap.cpp.o
[ 28%] Building CXX object statgen/CMakeFiles/statgen.dir/BgzfFileType.cpp.o
[ 30%] Building CXX object statgen/CMakeFiles/statgen.dir/BaseAsciiMap.cpp.o
[ 32%] Building CXX object statgen/CMakeFiles/statgen.dir/StringBasics.cpp.o
[ 33%] Building CXX object statgen/CMakeFiles/statgen.dir/StatGenStatus.cpp.o
[ 35%] Building CXX object statgen/CMakeFiles/statgen.dir/Tabix.cpp.o
[ 37%] Building CXX object statgen/CMakeFiles/statgen.dir/MathVector.cpp.o
[ 39%] Building CXX object statgen/CMakeFiles/statgen.dir/UncompressedFileType.cpp.o
[ 41%] Building CXX object statgen/CMakeFiles/statgen.dir/Generic.cpp.o
[ 43%] Building CXX object statgen/CMakeFiles/statgen.dir/MathMatrix.cpp.o
[ 45%] Building CXX object statgen/CMakeFiles/statgen.dir/Sort.cpp.o
[ 47%] Building CXX object statgen/CMakeFiles/statgen.dir/IndexBase.cpp.o
[ 49%] Building CXX object statgen/CMakeFiles/statgen.dir/CigarRoller.cpp.o
[ 50%] Building CXX object statgen/CMakeFiles/statgen.dir/Cigar.cpp.o
[ 52%] Building CXX object statgen/CMakeFiles/statgen.dir/BgzfFileTypeRecovery.cpp.o
[ 54%] Building CXX object statgen/CMakeFiles/statgen.dir/GzipHeader.cpp.o
[ 56%] Building CXX object statgen/CMakeFiles/statgen.dir/IntArray.cpp.o
[ 58%] Building CXX object statgen/CMakeFiles/statgen.dir/CharBuffer.cpp.o
[ 60%] Building C object statgen/CMakeFiles/statgen.dir/knetfile.c.o
Linking CXX static library libstatgen.a
[ 60%] Built target statgen
Scanning dependencies of target Vcf
[ 62%] Building CXX object libVcf/CMakeFiles/Vcf.dir/libVcfFile.cpp.o
Linking CXX static library libVcf.a
[ 62%] Built target Vcf
Scanning dependencies of target samtools
[ 64%] Building C object samtools/CMakeFiles/samtools.dir/bam_stat.c.o
[ 66%] Building C object samtools/CMakeFiles/samtools.dir/bedidx.c.o
[ 67%] Building C object samtools/CMakeFiles/samtools.dir/sam_opts.c.o
[ 69%] Building C object samtools/CMakeFiles/samtools.dir/bamtk.c.o
[ 71%] Building C object samtools/CMakeFiles/samtools.dir/bam_mate.c.o
[ 73%] Building C object samtools/CMakeFiles/samtools.dir/bam_sort.c.o
[ 75%] Building C object samtools/CMakeFiles/samtools.dir/bam.c.o
[ 77%] Building C object samtools/CMakeFiles/samtools.dir/bam_index.c.o
[ 79%] Building C object samtools/CMakeFiles/samtools.dir/bam_md.c.o
[ 81%] Building C object samtools/CMakeFiles/samtools.dir/bam_aux.c.o
[ 83%] Building C object samtools/CMakeFiles/samtools.dir/sample.c.o
[ 84%] Building C object samtools/CMakeFiles/samtools.dir/kprobaln.c.o
Linking C static library libsamtools.a
[ 84%] Built target samtools
Scanning dependencies of target VerifyBamID
[ 86%] Building CXX object CMakeFiles/VerifyBamID.dir/main.cpp.o
[ 88%] Building CXX object CMakeFiles/VerifyBamID.dir/SVDcalculator.cpp.o
[ 90%] Building CXX object CMakeFiles/VerifyBamID.dir/ContaminationEstimator.cpp.o
[ 92%] Building CXX object CMakeFiles/VerifyBamID.dir/MathGenMin.cpp.o
[ 94%] Building CXX object CMakeFiles/VerifyBamID.dir/MathGold.cpp.o
[ 96%] Building CXX object CMakeFiles/VerifyBamID.dir/Random.cpp.o
[ 98%] Building CXX object CMakeFiles/VerifyBamID.dir/SimplePileupViewer.cpp.o
[100%] Building CXX object CMakeFiles/VerifyBamID.dir/params.cpp.o
Linking CXX executable ../bin/VerifyBamID
/usr/bin/ld: /garnet/Tools/WGS_Analysis/Program/HTSlib/htslib-1.9/libhts.a(hfile_s3.o): undefined reference to symbol 'HMAC@@libcrypto.so.10'
//usr/lib64/libcrypto.so.10: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/VerifyBamID] Error 1
make[1]: *** [CMakeFiles/VerifyBamID.dir/all] Error 2
make: *** [all] Error 2

Could you give me some suggestions to solve the problem?

**Comment by Griffan** [comment]
It seems to be related to htslib and its linking to libcrypto. Could you try to confirm that first?

**Comment by omG0-hub** [comment]
when I executed the cmake step, I typed the command line 
"cmake -DHTS_INCLUDE_DIRS=/mnt/garnet/Tools/WGS_Analysis/Program/HTSlib/htslib-1.10.2/include/  -DHTS_LIBRARIES=/mnt/garnet/Tools/WGS_Analysis/Program/HTSlib/htslib-1.10.2/libhts.a .."

After that, continuously I run the make cmd but I found the error message.
Although I tried to execute the cmd  "make -lssl -lcrypto", the same error message was confirmed.

Especially, in part of the error message, "/usr/lib64/libcrypto.so.10: error adding symbols: DSO missing from command line" 
![image](https://user-images.githubusercontent.com/70621317/129679090-3cb52dd7-218d-41fb-b48d-5cdc271abf2f.png)
I found the "libcrypto.so.10" file already link that path.

**Comment by Griffan** [comment]
You need to pass "-lssl -lcrypto" to the compiler flags. Can you post your environment here if you cannot find a ready solution at link below: 
Depending on your environment, there are different ways to install htslib while linking to the required libraries:https://github.com/samtools/htslib/blob/develop/INSTALL
