### ISSUE TITLE
make fails with htslib 1.13 (1.11 OK)

### ISSUE THREAD

**Issue by myourshaw** [Griffan/VerifyBamID#29]
`cmake -DHTS_INCLUDE_DIRS=${INSTALL_DIR}/include/ -DHTS_LIBRARIES=${INSTALL_DIR}/lib/libhts.a ..
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Configuring done
-- Generating done
-- Build files have been written to: /hdd1/dnanexus/tmp/VerifyBamID/build
myourshaw@my-ubuntu:/hdd1/dnanexus/tmp/VerifyBamID/build$ sudo make
Scanning dependencies of target statgen
[  1%] Building CXX object statgen/CMakeFiles/statgen.dir/BaseAsciiMap.cpp.o
[  3%] Building CXX object statgen/CMakeFiles/statgen.dir/BaseUtilities.cpp.o
[  5%] Building CXX object statgen/CMakeFiles/statgen.dir/BgzfFileType.cpp.o
[  7%] Building CXX object statgen/CMakeFiles/statgen.dir/BgzfFileTypeRecovery.cpp.o
[  8%] Building CXX object statgen/CMakeFiles/statgen.dir/CharBuffer.cpp.o
[ 10%] Building CXX object statgen/CMakeFiles/statgen.dir/Cigar.cpp.o
[ 12%] Building CXX object statgen/CMakeFiles/statgen.dir/CigarRoller.cpp.o
[ 14%] Building CXX object statgen/CMakeFiles/statgen.dir/Error.cpp.o
[ 15%] Building CXX object statgen/CMakeFiles/statgen.dir/ErrorHandler.cpp.o
[ 17%] Building CXX object statgen/CMakeFiles/statgen.dir/FileType.cpp.o
[ 19%] Building CXX object statgen/CMakeFiles/statgen.dir/Generic.cpp.o
[ 21%] Building CXX object statgen/CMakeFiles/statgen.dir/GenomeSequence.cpp.o
[ 22%] Building CXX object statgen/CMakeFiles/statgen.dir/GzipFileType.cpp.o
[ 24%] Building CXX object statgen/CMakeFiles/statgen.dir/GzipHeader.cpp.o
[ 26%] Building CXX object statgen/CMakeFiles/statgen.dir/Hash.cpp.o
[ 28%] Building CXX object statgen/CMakeFiles/statgen.dir/IndexBase.cpp.o
[ 29%] Building CXX object statgen/CMakeFiles/statgen.dir/InputFile.cpp.o
[ 31%] Building CXX object statgen/CMakeFiles/statgen.dir/IntArray.cpp.o
[ 33%] Building CXX object statgen/CMakeFiles/statgen.dir/MathMatrix.cpp.o
[ 35%] Building CXX object statgen/CMakeFiles/statgen.dir/MathVector.cpp.o
[ 36%] Building CXX object statgen/CMakeFiles/statgen.dir/MemoryMap.cpp.o
[ 38%] Building CXX object statgen/CMakeFiles/statgen.dir/MemoryMapArray.cpp.o
[ 40%] Building CXX object statgen/CMakeFiles/statgen.dir/PhoneHome.cpp.o
[ 42%] Building CXX object statgen/CMakeFiles/statgen.dir/STLUtilities.cpp.o
[ 43%] Building CXX object statgen/CMakeFiles/statgen.dir/Sort.cpp.o
[ 45%] Building CXX object statgen/CMakeFiles/statgen.dir/StatGenStatus.cpp.o
[ 47%] Building CXX object statgen/CMakeFiles/statgen.dir/StringArray.cpp.o
[ 49%] Building CXX object statgen/CMakeFiles/statgen.dir/StringBasics.cpp.o
/hdd1/dnanexus/tmp/VerifyBamID/statgen/StringBasics.cpp: In static member function ‘static void String::check_vsnprintf()’:
/hdd1/dnanexus/tmp/VerifyBamID/statgen/StringBasics.cpp:1398:40: warning: ‘%5s’ directive output truncated writing 9 bytes into a region of size 5 [-Wformat-truncation=]
 1398 |         int check = snprintf(temp, 5, "%5s", "VSNPRINTF");
      |                                        ^~~   ~~~~~~~~~~~
In file included from /usr/include/stdio.h:866,
                 from /hdd1/dnanexus/tmp/VerifyBamID/statgen/StringBasics.h:21,
                 from /hdd1/dnanexus/tmp/VerifyBamID/statgen/StringBasics.cpp:18:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:35: note: ‘__builtin___snprintf_chk’ output 10 bytes into a destination of size 5
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |        __glibc_objsize (__s), __fmt,
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |        __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~           
[ 50%] Building CXX object statgen/CMakeFiles/statgen.dir/StringHash.cpp.o
[ 52%] Building CXX object statgen/CMakeFiles/statgen.dir/Tabix.cpp.o
[ 54%] Building CXX object statgen/CMakeFiles/statgen.dir/UncompressedFileType.cpp.o
[ 56%] Building C object statgen/CMakeFiles/statgen.dir/knetfile.c.o
[ 57%] Linking CXX static library libstatgen.a
[ 57%] Built target statgen
Scanning dependencies of target Vcf
[ 59%] Building CXX object libVcf/CMakeFiles/Vcf.dir/libVcfFile.cpp.o
[ 61%] Linking CXX static library libVcf.a
[ 61%] Built target Vcf
Scanning dependencies of target samtools
[ 63%] Building C object samtools/CMakeFiles/samtools.dir/bam.c.o
[ 64%] Building C object samtools/CMakeFiles/samtools.dir/bam_aux.c.o
[ 66%] Building C object samtools/CMakeFiles/samtools.dir/bam_index.c.o
[ 68%] Building C object samtools/CMakeFiles/samtools.dir/bam_mate.c.o
[ 70%] Building C object samtools/CMakeFiles/samtools.dir/bam_md.c.o
[ 71%] Building C object samtools/CMakeFiles/samtools.dir/bam_sort.c.o
[ 73%] Building C object samtools/CMakeFiles/samtools.dir/bam_stat.c.o
[ 75%] Building C object samtools/CMakeFiles/samtools.dir/bamtk.c.o
[ 77%] Building C object samtools/CMakeFiles/samtools.dir/bedidx.c.o
[ 78%] Building C object samtools/CMakeFiles/samtools.dir/kprobaln.c.o
[ 80%] Building C object samtools/CMakeFiles/samtools.dir/sam_opts.c.o
In file included from /usr/include/stdio.h:866,
                 from /hdd1/dnanexus/tmp/VerifyBamID/samtools/sam_opts.c:25:
In function ‘fprintf’,
    inlined from ‘parse_sam_global_opt’ at /hdd1/dnanexus/tmp/VerifyBamID/samtools/sam_opts.c:80:9:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:105:10: warning: ‘%s’ directive argument is null [-Wformat-overflow=]
  105 |   return __fprintf_chk (__stream, __USE_FORTIFY_LEVEL - 1, __fmt,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  106 |    __va_arg_pack ());
      |    ~~~~~~~~~~~~~~~~~
[ 82%] Building C object samtools/CMakeFiles/samtools.dir/sample.c.o
[ 84%] Linking C static library libsamtools.a
[ 84%] Built target samtools
Scanning dependencies of target VerifyBamID
[ 85%] Building CXX object CMakeFiles/VerifyBamID.dir/main.cpp.o
[ 87%] Building CXX object CMakeFiles/VerifyBamID.dir/SVDcalculator.cpp.o
[ 89%] Building CXX object CMakeFiles/VerifyBamID.dir/ContaminationEstimator.cpp.o
[ 91%] Building CXX object CMakeFiles/VerifyBamID.dir/MathGenMin.cpp.o
[ 92%] Building CXX object CMakeFiles/VerifyBamID.dir/MathGold.cpp.o
[ 94%] Building CXX object CMakeFiles/VerifyBamID.dir/Random.cpp.o
[ 96%] Building CXX object CMakeFiles/VerifyBamID.dir/SimplePileupViewer.cpp.o
/hdd1/dnanexus/tmp/VerifyBamID/SimplePileupViewer.cpp: In function ‘int mplp_func(void*, bam1_t*)’:
/hdd1/dnanexus/tmp/VerifyBamID/SimplePileupViewer.cpp:214:59: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘hts_pos_t’ {aka ‘long int’} [-Wformat=]
  214 |                 fprintf(stderr, "[%s] Skipping because %lld is outside of %d [ref:%d]\n",
      |                                                        ~~~^
      |                                                           |
      |                                                           long long int
      |                                                        %ld
  215 |                         __func__, b->core.pos, ref_len, b->core.tid);
      |                                   ~~~~~~~~~~~              
      |                                           |
      |                                           hts_pos_t {aka long int}
[ 98%] Building CXX object CMakeFiles/VerifyBamID.dir/params.cpp.o
[100%] Linking CXX executable ../bin/VerifyBamID
/usr/bin/ld: /usr/local/lib/libhts.a(hfile.o): in function `knet_open':
/hdd1/dnanexus/tmp/VerifyBamID/build/htslib-1.13/hfile.c:1357: multiple definition of `knet_open'; statgen/libstatgen.a(knetfile.c.o):knetfile.c:(.text+0x1240): first defined here
/usr/bin/ld: /usr/local/lib/libhts.a(hfile.o): in function `knet_dopen':
/hdd1/dnanexus/tmp/VerifyBamID/build/htslib-1.13/hfile.c:1374: multiple definition of `knet_dopen'; statgen/libstatgen.a(knetfile.c.o):knetfile.c:(.text+0xf30): first defined here
/usr/bin/ld: /usr/local/lib/libhts.a(hfile.o): in function `knet_read':
/hdd1/dnanexus/tmp/VerifyBamID/build/htslib-1.13/hfile.c:1386: multiple definition of `knet_read'; statgen/libstatgen.a(knetfile.c.o):knetfile.c:(.text+0xf60): first defined here
/usr/bin/ld: /usr/local/lib/libhts.a(hfile.o): in function `knet_seek':
/hdd1/dnanexus/tmp/VerifyBamID/build/htslib-1.13/hfile.c:1393: multiple definition of `knet_seek'; statgen/libstatgen.a(knetfile.c.o):knetfile.c:(.text+0x10a0): first defined here
/usr/bin/ld: /usr/local/lib/libhts.a(hfile.o): in function `knet_close':
/hdd1/dnanexus/tmp/VerifyBamID/build/htslib-1.13/hfile.c:1401: multiple definition of `knet_close'; statgen/libstatgen.a(knetfile.c.o):knetfile.c:(.text+0x11c0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/VerifyBamID.dir/build.make:218: ../bin/VerifyBamID] Error 1
make[1]: *** [CMakeFiles/Makefile2:159: CMakeFiles/VerifyBamID.dir/all] Error 2
make: *** [Makefile:114: all] Error 2
`

**Comment by Griffan** [comment]
Thanks for the feedback! 
At the moment for the sake of backward compatibility, I would recommend you to keep using 1.11. and I will try to draft a commit to fix this multiple definition issue.
