### ISSUE TITLE
Resource files for b38 exome

### ISSUE THREAD

**Issue by dtaliun** [Griffan/VerifyBamID#35]
Exome resource files for b38 1000g.phase3.10k.b38.exome.vcf.gz.dat.bed and 1000g.phase3.10k.b38.exome.vcf.gz.dat.mu need "chr" prefix. Without it, samtools gives errors e.g.: `[Warning::SimplePileup] initialization fail to parse region '8:120203752-120203752' ..`

**Comment by Griffan** [comment]
Thanks, fixed.

**Comment by Bioinf-usr** [comment]
Hi,

FYI, these files need to be updated also in the conda version. Because they are still missing the "chr" prefix and therefore leading to the error mentioned in this issue.

Hope you get a chance to fix them for the future users.

Thank you.

**Comment by Griffan** [comment]
> Hi,
> 
> FYI, these files need to be updated also in the conda version. Because they are still missing the "chr" prefix and therefore leading to the error mentioned in this issue.
> 
> Hope you get a chance to fix them for the future users.
> 
> Thank you.

@Bioinf-usr Thanks for your feedback! I will try to release a new tar ball once the recent PRs got merged.
