### ISSUE TITLE
Insufficient Available markers?

### ISSUE THREAD

**Issue by lingjoyo** [Griffan/VerifyBamID#39]
Here is my code
> docker run \
> -v /home/xxxxx/VerifyBamID/cram_files:/cram_files \
> -v /home/xxxxx/VerifyBamID/data:/data \
> -v /home/xxxxx/VerifyBamID/results:/results \
> griffan/verifybamid2:latest VerifyBamID  \
> --SVDPrefix /data/VerifyBamID_resources/1000g.phase3.100k.b38.vcf.gz.dat \
> --Reference /data/GRCh38_full_analysis_set_plus_decoy_hla.fa \
> --BamFile /cram_files/yyyy.cram \
> --Output /results/yyyy.cram 
### 
[SimplePileup] Total Number Bases: 215664
[SimplePileup] Total Number Markers: 7944
NOTICE - Number of marker in Reference Matrix:100000
NOTICE - Number of marker shared with input file:7944
NOTICE - Mean Depth:27.148036
NOTICE - SD Depth:30.930037
NOTICE - 7871 SNP markers remained after sanity check.
WARNING - 

Insufficient Available markers, check input bam depth distribution in output pileup file after specifying --OutputPileup

**Comment by Griffan** [comment]
Hi, @lingjoyo 
The problem could be your cram file has uneven coverage around the markers which are filtered by the sanity check step. The solution would be: 1) to change another set of markers 2) to disable sanity check with option in the help message.
