### ISSUE TITLE
Resource files for mouse data

### ISSUE THREAD

**Issue by xie186** [Griffan/VerifyBamID#41]
Hi, thank you for developing the tool. Could you please let me know whether you have tried this tool on mouse data? Which vcf file do you recommend to build the resource file? Thanks again!

**Comment by Griffan** [comment]
Hi, @xie186 
If your specific mouse genome is diploid, in principle this tool can be applied to your files. However, the resource files require a diverse population level genotype VCF as a reference panel. 
If you don't have this population level genotype VCF. You can still try to use VB1 to test on your dataset .
