### ISSUE TITLE
After Downloading via Docker (and singularity), Fatal Error Appears: No such file or directory

### ISSUE THREAD

**Issue by bioinfo-fiend** [Griffan/VerifyBamID#48]
After downloading verifybamid2 both ways either via docker or singularity, I continue getting an error. I tried initially via source code but this does not work either as I come across _htslibrary_ issue when trying to run the _make_ command, as described in previous issue as seen here https://github.com/Griffan/VerifyBamID/issues/18    

```
FATAL ERROR -
Failed opening file /hpc/annotation/variants/resources/gnomad_hg38_exome.r2.1.AF_0.01-0.2.biallelic.vcf.gz - No such file or directory

Exiting due to ERROR:
	Exception was thrown
```

Download via singularity:

`singularity pull docker://griffan/verifybamid2`

Command to run image 

```
singularity exec verifybamid2_latest.sif VerifyBamID \
 --RefVCF /hpc/annotation/variants/resources/gnomad_hg38_exome.r2.1.AF_0.01-0.2.biallelic.vcf.gz \
 --Reference /hpc/references/hg38bundle/v0/Homo_sapiens_assembly38.fasta
```

**Comment by Griffan** [comment]
Does this cmdline work on your side?
```
docker run -v  /localPath/localDirectory:/VerifyBamID/localDirectory  griffan/verifybamid2:v1.0.6 VerifyBamID --SVDPrefix /VerifyBamID/resource/1000g.phase3.10k.b37.vcf.gz.dat --BamFile  /VerifyBamID/localDirectory/targetSample.bam --Reference  /VerifyBamID/localDirectory/hs37d5.fa 
```

**Comment by johnbakerh** [comment]
I get the following error:

```
Digest: sha256:c208ca10a0351ea0c694b43d877fb8098b28c75482374cdd22172d524f48eecc
Status: Downloaded newer image for griffan/verifybamid2:v1.0.6
docker: Error response from daemon: Mounts denied:
The path /localPath/localDirectory is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
ERRO[0009] error waiting for container: context canceled
```

**Comment by johnbakerh** [comment]
I've tried downloading via bioconda and also get another error when running the following command:

```
verifybamid2 --Verbose \
--RefVCF /hpc/annotation/variants/resources/gnomad_hg38_exome.r2.1.AF_0.01-0.2.biallelic.vcf.gz \ 
--Reference /hpc/references/hg38bundle/v0/Homo_sapiens_assembly38.fasta
```

```

Cannot correspond command line parameter /hpc/pmc_gen/references/hg38bundle/v0/Homo_sapiens_assembly38.fasta (#3) to any of the options


FATAL ERROR -
Problems encountered parsing command line:

Cannot correspond command line parameter /hpc/pmc_gen/references/hg38bundle/v0/Homo_sapiens_assembly38.fasta (#3) to any of the options

```

**Comment by johnbakerh** [comment]
Using default resources provided on your repo I get the following as well:
`
verifybamid2 --Reference hpc/miniconda-4.12.0/envs/verifybamid2_env/share/verifybamid2-2.0.1-3/resource/test/chr20.fa.gz --BamFile /hpc/miniconda-4.12.0/envs/verifybamid2_env/share/verifybamid2-2.0.1-3/resource/test/test.bam --SVDPrefix /hpc/miniconda-4.12.0/envs/verifybamid2_env/share/verifybamid2-2.0.1-3/resource/1000g.100k.b38.vcf.gz.dat`

Initialize from FullLLKFunc(int dim, ContaminationEstimator* contPtr)
Open file:/hpc/miniconda-4.12.0/envs/verifybamid2_env/share/verifybamid2-2.0.1-3/resource/1000g.100k.b38.vcf.gz.dat.bed	 failed, exit!

**Comment by johnbakerh** [comment]
Latest error with Singularity/Docker

Open file:/hpc/algorithms/VerifyBamID/resource/exome/1000g.phase3.10k.b38.exome.vcf.gz.dat.bed     failed, exit

Command line:

```
singularity exec verifybamid2_latest.sif VerifyBamID \ 
--BamFile /hpc/resources/testWXS.bam \
--Reference /hpc/Homo_sapiens_assembly38.fasta \
--SVDPrefix /hpc/algorithms/VerifyBamID/resource/exome/1000g.phase3.10k.b38.exome.vcf.gz.dat
```

**Comment by bioinfo-fiend** [comment]
there was an issue with the mount where I was running on the hpc, will close this issue then.
