### ISSUE TITLE
make fails with htslib 1.11

### ISSUE THREAD

**Issue by nalawu** [Griffan/VerifyBamID#49]
Hi Griffan,
    I've tried to install VerifyBamID using source code ,as following
cmake -DHTS_INCLUDE_DIRS=/root/software/test/htslib-1.11  -DHTS_LIBRARIES=/root/software/test/htslib-1.11/libhts.a ..
cmake has no problem ,but when I continue to do make ,the error has reported like this : 

[ 98%] Building CXX object CMakeFiles/VerifyBamID.dir/params.cpp.o
[100%] Linking CXX executable ../bin/VerifyBamID
/usr/bin/ld: /root/software/test/htslib-1.11/libhts.a(hfile_s3.o): undefined reference to symbol 'EVP_sha256@@OPENSSL_1_1_0'
//usr/lib64/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/VerifyBamID.dir/build.make:219: ../bin/VerifyBamID] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/VerifyBamID.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

So what's the problem of this ,which version of htslib is available for installation?
I hope you will reply as soon as possible,THANKS.

**Comment by Griffan** [comment]
Could you try `make LIBS="-lssl -lcrypto"`to fix the issue?

**Comment by nalawu** [comment]
> 

I've tried it ,but it still reports the same error
[100%] Linking CXX executable ../bin/VerifyBamID
/usr/bin/ld: /root/software/test/htslib-1.11/libhts.a(hfile_s3.o): undefined reference to symbol 'EVP_sha256@@OPENSSL_1_1_0'
//usr/lib64/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/VerifyBamID.dir/build.make:219: ../bin/VerifyBamID] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/VerifyBamID.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

**Comment by nalawu** [comment]
> /usr/bin/ld: /root/software/test/htslib-1.11/libhts.a(hfile_s3.o): undefined reference to symbol 'EVP_sha256@@OPENSSL_1_1_0'



> Could you try `make LIBS="-lssl -lcrypto"`to fix the issue?

My OpenSSL's version is :
[root@ecs-70437 htslib-1.11]# openssl version -a
OpenSSL 1.1.1k  FIPS 25 Mar 2021
built on: Wed Jul 21 11:11:34 2021 UTC
platform: linux-x86_64
options:  bn(64,64) md2(char) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
OPENSSLDIR: "/etc/pki/tls"
ENGINESDIR: "/usr/lib64/engines-1.1"
Seeding source: os-specific
engines:  rdrand dynamic

**Comment by Griffan** [comment]
Could you confirm if your htslib is built successfully without any errors or warnings? and the `samtools` can run smoothly first?

**Comment by nalawu** [comment]
> LIBS="-lssl -lcrypto"



> Could you confirm if your htslib is built successfully without any errors or warnings? and the `samtools` can run smoothly first?

My samtools can work properly，I've tested it as following 
/root/software/samtools-1.15/bin/samtools index 19O014065_sorted_dedup.bam
and it can sucessfully generate 19O014065_sorted_dedup.bam.bai

htslib-1.11 can be built sucessfully when using the following code:
autoheader     # If using configure, generate the header template...
autoconf       # ...and configure script (or use autoreconf to do both)
./configure    # Optional but recommended, for choosing extra functionality
make
make install

And I guess if there is no -lssl -lcrypto in htslib-1.11,so when I make htslib-1.11 again ,I've tried it using the following code:
autoheader     # If using configure, generate the header template...
autoconf       # ...and configure script (or use autoreconf to do both)
./configure    # Optional but recommended, for choosing extra functionality
make LIBS="-lssl -lcrypto"
then it reports the error : 
/usr/bin/ld: libhts.a(bgzf.o): undefined reference to symbol 'inflateEnd'
//usr/lib64/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:371: bgzip] Error 1

So it suggests that the problem is that htslib-1.11 doesn't have those libs ?

**Comment by Griffan** [comment]
I found this issue addresses the exact compiling error you saw, please let me know if the solution fixes yours: https://github.com/tony-kuo/eagle/issues/4

**Comment by nalawu** [comment]
> I found this issue addresses the exact compiling error you saw, please let me know if the solution fixes yours: [tony-kuo/eagle#4](https://github.com/tony-kuo/eagle/issues/4)

I've tried it ,it's not worked .But I think the solution maybe I try to let htslib find the -lssl -lcrypto ;I'm going reinstall my OpenSSL ,and add it's lib into my /etc/ld.so.conf.d/ mentioned by  https://www.hostnextra.com/kb/how-to-install-openssl-1-1-1i-in-centos-8/
If I've solved it ,I reply to you ,Thank for your help .

**Comment by nalawu** [comment]
> I found this issue addresses the exact compiling error you saw, please let me know if the solution fixes yours: [tony-kuo/eagle#4](https://github.com/tony-kuo/eagle/issues/4)

Hi Griffan,
    It has been successfully built .
"
[ 98%] Building CXX object CMakeFiles/VerifyBamID.dir/params.cpp.o
[100%] Linking CXX executable ../bin/VerifyBamID
[100%] Built target VerifyBamID

[root@ecs-70437 build]# make test
Running tests...
Test project /root/software/VerifyBamID/build
    Start 1: myTest1
1/1 Test #1: myTest1 ..........................   Passed    1.09 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   1.09 sec
[root@ecs-70437 build]# 

[root@ecs-70437 bin]# /root/software/VerifyBamID/bin/VerifyBamID
VerifyBamID2: A robust tool for DNA contamination estimation from sequence reads using ancestry-agnostic method.

 Version:2.0.1
 Copyright (c) 2009-2020 by Hyun Min Kang and Fan Zhang
 This project is licensed under the terms of the MIT license.
"

But I can't tell the reason exactly now ,Firstly I reinstall the openssl as the method mentioned by  https://www.hostnextra.com/kb/how-to-install-openssl-1-1-1i-in-centos-8/ after I uninstall the old one ,However the new openssl still didn't work .Then I uninstall the new openssl and reset the environment as nothing happend .and when I rebuilt VerifyBamID2 it has built smoothly.

When I have free time ,I recall my step ,and post the reason on this issue .
Thanks a lot for your help.
