### ISSUE TITLE
make VerifyBamID compile error

### ISSUE THREAD

**Issue by SenatorFrito** [Griffan/VerifyBamID#5]
commit 20fa6fe705c984576be59086a52ebd26062a4a4c 

I had a number of compile errors eliminated by sourcing adequate configuration and/or compiler versions: 
 gcc 4.9.1, cmake 3.5.1, zlib 1.2.6, autoconf 2.69, automake1.14

but 'make VerifyBamID' throws error: 
```
VerifyBamID/ContaminationEstimator.h:106:23:               \
    error: assignment of read-only location                \
    '(& tPC)->std::vector<_Tp, _Alloc>::operator[]<double, \
        std::allocator<double> >(((std::vector<double>::size_type)i))'
                 tPC[i]=(tPC[i]-ptr->muv[i])/ptr->sdv[i];
                       ^  
```

**Comment by Griffan** [comment]
thanks for your report. It should be fine now.

**Comment by SenatorFrito** [comment]
We have a good binary. Thanks for looking at this.
