### ISSUE TITLE
Generating resource files

### ISSUE THREAD

**Issue by z1242099843** [Griffan/VerifyBamID#51]
Hi,
I have a VCF file containing only variant positions and allele frequency information without genotype data for any sample. When I tried to create resource files using VB2, an error occurred. I would like to manually generate the resource files and I understand the contents of .bed and .mu files, but I do not know how the .UD file is generated. I wonder if .UD file is related to genotype data, and how I can generate it without the genotype data.

Thanks for any help you can give me.

**Comment by Griffan** [comment]
Hi, the resource files are generated based on the genotype matrix represented by VCF GT columns. You do need the genotype data to produced customized resource files.
