### ISSUE TITLE
Can verifyBamID2 be used to detect contamination in non-human species data?

### ISSUE THREAD

**Issue by maruiqi0710** [Griffan/VerifyBamID#52]
I have already sequenced a batch of fungus data and would like to use verifyBamID2 to detect contamination in the WGS data. I note that the examples mentioned in _Ancestry-agnostic estimation of DNA sample contamination from sequence reads_ are all human sequencing data. I would like to know whether verifyBamID2 can be used for other non-human species.
Thanks.

**Comment by Griffan** [comment]
In theory, you can use it on non-human diploid species.
