### ISSUE TITLE
--max-depth Doesn't Do Anything?

### ISSUE THREAD

**Issue by michaelsykes** [Griffan/VerifyBamID#56]
I am experiencing an issue similar to a previous one, where WES data at high depth can sometimes give abnormally high contamination estimates. When the samples are downsampled to lower depth, those estimates return to near-zero.

I though using the --max-depth flag might help, but it doesn't actually seem to do anything. For example this is part of STDERR after setting --max-depth 10:

```
   Construction of SVD Auxiliary Files : --RefVCF [Empty]
                        Pileup Options : --min-BQ [13], --min-MQ [2],
                                         --adjust-MQ [40], --max-depth [10],
                                         --no-orphans, --incl-flags [1040],
                                         --excl-flags [1796]
                    Deprecated Options : --UDPath [Empty], --MeanPath [Empty],
                                         --BedPath [Empty]


Initialize from FullLLKFunc(int dim, ContaminationEstimator* contPtr)
[SimplePileup] 1 sample(s) in 1 input file(s)
[SimplePileup] Set max per-file depth to 8000
```
You can see that the option is correctly reflected in the "Pileup Options" section, but reverts to 8000 below. Am I misinterpreting this option or is this a bug?

**Comment by Griffan** [comment]
Thanks for reporting this behavior. 
Did you start it from the BAM file or from the Pileup file? The max-depth option currently only works with BAM/CRAM file input. The pileup file was introduced mainly for the purpose of debugging and will not benefit from as many options as the BAM file input does.

**Comment by michaelsykes** [comment]
This was from BAM input.

I did find an interesting workaround. I recompiled htslib 1.11 and replaced the hardcoded limit of 8000 with a limit of just 50 (I also tested 100 but it wasn't low enough), and also altered the if statement where that limit is checked. 

Then I recompiled verifyBamID2 using that new htslib. This completely eliminated the depth-dependent effects I was seeing, and the incorrect high contamination estimates at high coverage.

I also checked this new version against synthetic data with contamination levels from 1% and above, and even with a max depth of 50 it was still able to accurately detect 1% contamination in samples.

**Comment by Griffan** [comment]
@michaelsykes thanks for digging into this issue. I also located the culprit in my code:https://github.com/Griffan/VerifyBamID/blob/7e7172c2b45f61c72d35d94708a7a5c2f271ee3a/SimplePileupViewer.cpp#L372
This was inherited from an earlier version of samtools pileup code, I will try to fix it soon.

**Comment by Griffan** [comment]
@michaelsykes it has been fixed.
