### ISSUE TITLE
Error when running VerifyBamID with more than 4PCs

### ISSUE THREAD

**Issue by lo2811** [Griffan/VerifyBamID#58]
Hello,

I am using VerifyBamID2 on some WES samples and would like to run VerifyBamID with 10PC, and ran into an error:

`--NumPC only permits as large as 4 PCs when using SVD files in ${verifybamID}/resource/ directory`

I tried 2 ways:
1. Remove SVDPrefix from the command
2. Use --RefVCF to specify the reference vcf to use

Both solutions gave me the same error. I installed VerifyBamID using the V2.0.1 release source code (tar.gz) (01/13/2021).

Can you please let me know what needs to be done here so I can use 10PC?

Thank you very much!

**Comment by Griffan** [comment]
Hi @lo2811, you can use the parameter '--NumPC 10' when you try to generate the resource files from the --RefVCF, for example:
`
VerifyBamID --RefVCF ReferencePanel.vcf.gz --Reference ./resource/test/chr20.fa.gz --NumPC 10
`

**Comment by lo2811** [comment]
Thank you for your reply, Griffan.

Unfortunately, I used --RefVCF and still received the same error :(

**Comment by hyunminkang** [comment]
Did you create your own reference? The resource file provided by default only contains 4 PCs max.

**Comment by Griffan** [comment]
Hi @lo2811, I just pushed a patch to fix this problem by moving --NumPC check into PC files reading. Let me know if it works on your end.

**Comment by lo2811** [comment]
Hi @Griffan , I just want to follow up with you that everything is running great for me now. Thank you very much for the instruction + patch.
