### ISSUE TITLE
Error message during installation

### ISSUE THREAD

**Issue by jjfarrell** [Griffan/VerifyBamID#6]
I am getting the following error message during the installation. Any suggestions?  

cd build
[farrell@scc-hadoop build]$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /restricted/projectnb/genpro/github/VerifyBamID/build
[farrell@scc-hadoop build]$ make
[ 13%] Built target HTSLIB
[ 65%] Built target statgen
[ 67%] Built target Vcf
[ 86%] Built target samtools
[ 88%] Building CXX object CMakeFiles/VerifyBamID.dir/main.cpp.o
In file included from /restricted/projectnb/genpro/github/VerifyBamID/main.cpp:26:
/restricted/projectnb/genpro/github/VerifyBamID/ContaminationEstimator.h: In constructor 'ContaminationEstimator::fullLLKFunc::fullLLKFunc()':
/restricted/projectnb/genpro/github/VerifyBamID/ContaminationEstimator.h:76: error: 'nullptr' was not declared in this scope
/restricted/projectnb/genpro/github/VerifyBamID/main.cpp: In function 'int execute(int, char**)':
/restricted/projectnb/genpro/github/VerifyBamID/main.cpp:179: error: expected initializer before ':' token
/restricted/projectnb/genpro/github/VerifyBamID/main.cpp:194: error: could not convert 'fout.std::basic_ofstream<_CharT, _Traits>::close [with _CharT = char, _Traits = std::char_traits<char>]()' to 'bool'
/restricted/projectnb/genpro/github/VerifyBamID/main.cpp:195: error: expected primary-expression before '}' token
/restricted/projectnb/genpro/github/VerifyBamID/main.cpp:195: error: expected ')' before '}' token
/restricted/projectnb/genpro/github/VerifyBamID/main.cpp:195: error: expected primary-expression before '}' token
/restricted/projectnb/genpro/github/VerifyBamID/main.cpp:195: error: expected ';' before '}' token
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-result"
make[2]: *** [CMakeFiles/VerifyBamID.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/VerifyBamID.dir/all] Error 2
make: *** [all] Error 2

**Comment by Griffan** [comment]
Could you take a look at your GCC version? I guess that could be the problem. It's recommended to upgrade you compiler to be at least version 4.6. Let me know if that resolves you situation.

**Comment by jjfarrell** [comment]
Thanks! The version of cmake was old and pointing to an old version of gcc.  Once I fixed that the  VerifyBamID compiled fine.
