### ISSUE TITLE
Check file system calls succeed

### ISSUE THREAD

**Issue by ThomasHickman** [Griffan/VerifyBamID#7]
The operator `<<` for `ofstream` instances doesn't throw an exception. As the method `bad` (http://en.cppreference.com/w/cpp/io/basic_ios/bad) is not being checked (e.g. in https://github.com/Griffan/VerifyBamID/blob/915d47fbf6570f2655d10e66fa7954e318b14ead/main.cpp#L230), this means that write errors are not checked and this process is returning a success code when it should be failing with an error message.
One proposed solution is to create a wrapper function that wraps `fout` with a function that calls `exceptions(std::ios::badbit | std::ios::failbit);`, such that exceptions are propagated. I can have a look at submitting a pull request for this.

**Comment by Griffan** [comment]
thanks for your submission, I have updated related code
